
spring:
  profiles:
    active: testdocker
server:
  port: 80
---
spring:
  config:
    activate:
      on-profile: testdocker
  datasource:
    url: jdbc:mariadb://localhost:39907/codingtest
    username: root
    password: 1111
    initialization-mode: always
    schema: classpath*:database/testdocker/schema.sql

    hikari:
      auto-commit: true

  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging.level:
  org.hibernate.SQL: debug
